
//bluetooth sensors
export const BLE_MANAGER_START = 'BLE_MANAGER_START'
export const BLE_MANAGER_START_SUCCESS = 'BLE_MANAGER_START_SUCCESS'
export const BLE_MANAGER_START_FAIL = 'BLE_MANAGER_START_FAIL'

export const BLE_MANAGER_DISCOVERED_SMTH = 'BLE_MANAGER_DISCOVERED_SMTH'

export const BLE_MANAGER_SCAN_STARTED = 'BLE_MANAGER_SCAN_STARTED'
export const BLE_MANAGER_SCAN_STOPPED = 'BLE_MANAGER_SCAN_STOPPED'

export const BLE_MANAGER_CONNECT_TO_SENSOR = 'BLE_MANAGER_CONNECT_TO_SENSOR'
export const BLE_MANAGER_CONNECT_TO_SENSOR_SUCCESS = 'BLE_MANAGER_CONNECT_TO_SENSOR_SUCCESS'
export const BLE_MANAGER_CONNECT_TO_SENSOR_FAIL = 'BLE_MANAGER_CONNECT_TO_SENSOR_FAIL'

export const BLE_MANAGER_DISCONNECT_FROM_SENSOR = 'BLE_MANAGER_DISCONNECT_FROM_SENSOR'
export const BLE_MANAGER_DISCONNECT_FROM_SENSOR_SUCCESS = 'BLE_MANAGER_DISCONNECT_FROM_SENSOR_SUCCESS'
export const BLE_MANAGER_DISCONNECT_FROM_SENSOR_FAIL = 'BLE_MANAGER_DISCONNECT_FROM_SENSOR_FAIL'

export const CHECK_IF_SENSOR_CONNECTED = 'CHECK_IF_SENSOR_CONNECTED'
export const CHECK_IF_SENSOR_CONNECTED_SUCCESS = 'CHECK_IF_SENSOR_CONNECTED_SUCCESS'
export const CHECK_IF_SENSOR_CONNECTED_FAIL = 'CHECK_IF_SENSOR_CONNECTED_FAIL'

export const ON_SENSOR_DATA_RECEIVED = 'ON_SENSOR_DATA_RECEIVED'

export const SWITCH_TAB = 'SWITCH_TAB'

export const SAVE_SENSORS = 'SAVE_SENSORS'
export const SAVE_SENSORS_SUCCESS = 'SAVE_SENSORS_SUCCESS'
export const SAVE_SENSORS_FAIL = 'SAVE_SENSORS_FAIL'

export const LOAD_SENSORS = 'LOAD_SENSORS'
export const LOAD_SENSORS_SUCCESS = 'LOAD_SENSORS_SUCCESS'
export const LOAD_SENSORS_FAIL = 'LOAD_SENSORS_FAIL'

